@startuml
'https://plantuml.com/class-diagram

'Make public/private/etc show up as character rather than colored circle.
skinparam classAttributeIconSize 0

abstract class AbstractAnimal {
    + AbstractAnimal()
    + {abstract} eat()
    + {abstract} methodA1()
    + methodA2()
}

abstract class AbstractSkyThing {
    + AbstractSkyThing()
    + {abstract} setAltitude()
    + methodST1()
    + methodST2()
}

class Dog {
    +Dog()
    +eat()
    +methodA1()
}
AbstractAnimal <|-- Dog

class Cloud {
    + Cloud()
    + setAltitude()
}
AbstractSkyThing <|-- Cloud

class Bird {
    +eat()
    +setAltitude()
}

@enduml